# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        NODE_VERSION: 16

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"

      
      - name: Deploy to Debian Server/actions
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Print working directory
        run: pwd
        
      - name: Debug information
        run: |
          echo "GitHub workspace: ${GITHUB_WORKSPACE}"
          ls -R "${{ github.workspace }}"
          ls -l ${{ github.workspace }}
          git log --format=oneline -n 5

      - name: Determine changed files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

      - name: Display changed files
        run: cat changed_files.txt

      - name: Print working directory
        run: pwd
        
      - name: Enable Universe repository
        run: sudo add-apt-repository universe

      - name: Install git-ftp
        run: sudo apt-get update && sudo apt-get install -y git-ftp

      - name: Deploy to Debian Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_IP }}
          username: ${{ secrets.TEST_SSH_USERNAME }}
          password: ${{ secrets.TEST_SSH_PASSWORD }}
          port: ${{ secrets.TEST_SSH_PORT }}
          
          script: |
            cd ${{ github.workspace }}
            git ftp push --user ${{ secrets.TEST_SSH_USERNAME }} --passwd ${{ secrets.TEST_SSH_PASSWORD }} ftp://${{ secrets.TEST_SSH_IP }}:${{ secrets.TEST_SSH_PORT }}/var/www/html/production2/
      # script: |      
      #   mkdir -p /var/www/html/production1/  
      #   xargs -a ${GITHUB_WORKSPACE}/changed_files.txt -I {} rsync -avz --delete ${GITHUB_WORKSPACE}/{} /var/www/html/production1/ 
      # Ensure production directory exists
      # Upload only merged files (optional modification)
      # /home/runner/work/Deployment-stuff/Deployment-stuff
      # mkdir -p /var/www/html/production/
      # rsync -avz --delete ./home/ /var/www/html/production/

      # - name: Install sshpass
      #   run: sudo apt-get install -y sshpass

      # - name: Install rsync
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y rsync


      # # - name: Debug information
      # #   run: |
      # #     set -x
      # #     sshpass -p ${{ secrets.TEST_SSH_PASSWORD }} scp -r -P 22 /home/runner/work/Deployment-stuff/Deployment-stuff/  toor@62.4.27.3:/var/www/html/production/
      # - name: Deploy using rsync
      #   run: |
      #     rsync -av -e "sshpass -p '${{ secrets.TEST_SSH_PASSWORD }}' ssh -p 22" \
      #     /home/runner/work/Deployment-stuff/Deployment-stuff/ \
      #     ${{ secrets.TEST_SSH_USERNAME }}@${{ secrets.TEST_SSH_IP }}:/var/www/html/production/
      #   env:
      #     SSH_PORT: ${{ secrets.TEST_SSH_PORT }}
