# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        NODE_VERSION: 16

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Debug information
        run: |
          echo "GitHub workspace: ${GITHUB_WORKSPACE}"
          ls -R "${{ github.workspace }}"
          ls -l ${{ github.workspace }}


      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync


      # - name: Debug information
      #   run: |
      #     set -x
      #     sshpass -p ${{ secrets.TEST_SSH_PASSWORD }} scp -r -P 22 /home/runner/work/Deployment-stuff/Deployment-stuff/  toor@62.4.27.3:/var/www/html/production/
      - name: Deploy using rsync
        run: |
          rsync -av -e "sshpass -p '${{ secrets.PRODUCTION_SSH_PASSWORD }}' ssh -p ${SSH_PORT}" \
          /home/runner/work/Deployment-stuff/Deployment-stuff/ \
          ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_IP }}:/var/www/html/production/
        env:
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
