# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Staging
        run: sshpass -p ${{ secrets.TEST_SSH_PASSWORD }} scp -r ./path/to/local/files/* ${{ secrets.TEST_SSH_USERNAME }}@${{ secrets.TEST_SSH_IP }}:/var/www/html/production/
          
